src/api/api.py
src/factories/__init__.py
src/factories/resource_assigner_factories.py
src/resource_assigner/api.py
src/resource_assigner/models.py
src/resource_assigner/schemas.py
src/resource_assigner/services.py
src/resource_assigner/tests/services/test_assignment_rule_criteria.py
src/resource_assigner/tests/services/test_assignment_rule_service.py
src/resource_assigner/tests/services/test_task_resource_assigment.py

1. Working on Resource Assigner APIs.
2. Resource Assigner services and test cases has been completed
Question about `TaskResourceAssigment`
```bash
class TaskResourceAssigment(BaseModel):
task = models.ForeignKey(Task, on_delete=models.DO_NOTHING)
resource_group = models.ForeignKey(ResourceGroup, on_delete=models.DO_NOTHING)
resources = models.ManyToManyField(
Resource, related_name="task_resource_assigments", blank=True, null=True
)
resource_count = models.IntegerField(blank=True, null=True)
use_all_resources = models.BooleanField()
is_direct = models.BooleanField()
class Meta:
db_table = "task_resource_assigment"
def clean(self):
if self.resources and self.resource_group != 1:
raise ValidationError(
"Resource group must be 'All Resources' if resources are selected"
)
``` 
The …

Resource Assigner Services and APIs

---

src/api/api.py
src/resource_calendar/api.py
src/resource_calendar/schemas.py

1. WeeklyShiftTemplates
2. WeeklyShiftTemplateDetails
3. OperationalExceptionTypes
4. OperationalExceptions

Resource calender APIs and Schemas

---

src/common/admin.py
src/job_manager/admin.py
src/resource_assigner/admin.py
src/resource_calendar/admin.py
src/resource_manager/admin.py

1. Registred all models in the django admin panel.

registered all models in the django admin panel

---

src/templates/base/main.html

Frontend (main.html) had multiple head and title tags. Removed unwanted title and head tags.

fix: bug related to head and title tag

---

src/common/views.py
src/resource_assigner/migrations/0023_remove_assignmentconstraint_is_active_and_more.py

fixed the unordered object list warning for list view models

[fix-72]: unordered object list warning fixed

---

src/common/views.py

- Fix for form fields being editable in view mode

[85] Fix: Disabled fields for read-only view

---

src/resource_assigner/utils.py
src/resource_assigner/views.py

fixed - assigment rules match API and fixed the bug

[fix-77] added proper error handling and bug fix

---

src/scheduler/api.py
src/scheduler/services.py

- Added UTC timezone to scheduler timestamps
- Some auto-formatting for imports

feat: Make scheduler run times timezone-aware

---

src/common/forms.py
src/resource_assigner/forms.py
src/templates/objects/details.html

[fix-82]: frontend updated for boolean field form appearance

---

src/job_manager/views.py

#138 Added assignment constraints in the task page

enhancement: added assignment constraints in the task page

---

src/job_manager/services.py
src/resource_assigner/views.py

- Updated Gantt Task data to display multiple resource names
- Updated code affected by TaskResourceAssignment model changes

Fix: multiple resources gantt task data

---

src/job_manager/api/chart_data.py
src/job_manager/services.py
src/job_manager/urls.py

Sample output data:
```
[
{
"pID": 0,
"pName": "Machine 1",
"pStart": "",
"pEnd": "",
"pClass": "gtaskblue",
"pLink": "",
"pMile": 0,
"pRes": "",
"pComp": 0,
"pGroup": 1,
"pOpen": 1,
"pDepend": "",
"pCaption": "",
"pNotes": "",
},
{
"pID": 1,
"pName": "Machine 2",
"pStart": "",
"pEnd": "",
"pClass": "gtaskblue",
"pLink": "",
"pMile": 0,
"pRes": "",
"pComp": 0,
"pGroup": 1,
"pOpen": 1,
"pDepend": "",
"pCaption": "",
"pNotes": "",
},
{
"pID": 2,
"pName": "User 1",
"pStart": "",
"pEnd": "",
"pClass": "gtaskblue",
"pLink": "",
"pMile": 0,
"pRes": "",
"pComp": 0,
"pGroup": 1,
"pOpen": 1,
"pDepend": "",
"pCaption": "",
"pNotes": "",
},
{
"pID": 3,
"pName": "User 2",
"pStart": "",
"pEnd": "",
"pClass": "gtaskblue",
"pLink": "",
"pMile": 0,
"pRes": "",
"pComp": 0,
"pGroup": 1,
"pOpen": 1, …
```

feat: API endpoint for Resource Gantt Chart

---

src/common/views/crud_view.py

1. Resolved the issue that occurred when attempting to create additional models.

bug fix - create update form

---

src/common/utils/ordered_models.py
src/job_manager/views.py
src/microbatching/migrations/0001_initial.py
src/microbatching/views/microbatch_flow.py
src/microbatching/views/microbatch_rule.py
src/resource_assigner/views.py
src/resource_calendar/views.py
src/resource_manager/views.py
src/scheduler/urls.py
src/scheduler/views.py

1. Added text fields to the `SEARCH_FIELDS` parameter across the views for all models.

fix: updated search fields for all models in views

---

src/common/views/crud_view.py
src/common/views/table_view.py
src/job_manager/views.py
src/scheduler/services.py
src/templates/objects/list.html

- Added filtered table view that only displays parent `Tasks`

feat: Parent task view

---

src/scheduler/services.py

- Updated scheduler run, so it could proceed even with unscheduled tasks.
- Unscheduled tasks are now included in the log, instead of interrupting the scheduler flow.

fix: Allow scheduler to proceed with unscheduled tasks.

---

src/api/utils.py
src/job_manager/models/job.py
src/job_manager/models/task.py
src/job_manager/services.py
src/microbatching/services/microbatch_flow.py
src/resource_calendar/models.py
src/resource_calendar/tests/services/test_weekly_shift_template_details_service.py
src/scheduler/api/scheduler_run.py
src/scheduler/services.py

1. Resolved the issue with task creation by adding the `parent ID` in the service.  
2. Removed the weekly shift template details validations for `start_time` and `end_time`.
3. code formatting

fixed: API issues

---

src/scheduler/urls.py
src/scheduler/utils.py
src/scheduler/views.py

- Added API endpoint for scheduler run

feat: Scheduler API trigger

---

requirements.txt
src/factryflow/settings/components/common.py

Tested Django Waffle with views, templates, and forms by creating switches and flags. It's working as our requirement.
1. Migrate the database to merge django-waffle tables
2. add `flags` or `switches` using django admin under the `DJANGO-WAFFLE` app models.

feature: feature flags updates

---

src/factryflow/settings/components/common.py
src/job_manager/services/gantt_chart.py
src/resource_assigner/utils.py
src/scheduler/services/scheduler_run.py

- Added error handling for scheduler run; Excluded tasks with no assignments or constraints
- EXTRA: Added NinjaJWT config
- Minor code fixes and added logging

fix: scheduler process error handling

---

src/common/views/table_view.py
src/job_manager/views/job.py
src/templates/job_manager/job/prioritization.html

fixed the priority manager error if there are no jobs

fix: priority jobs issue fixed

---

src/common/views/crud_view.py

Fixed the server error caused by missing nested criteria data.

fix: nested criteria data not found error

---

src/common/utils/constants.py
src/common/utils/criteria.py
src/common/views/crud_view.py
src/microbatching/services/microbatch_rule.py
src/microbatching/utils/microbatch_rule.py
src/resource_assigner/services/rule_criteria.py
src/resource_assigner/utils.py
src/templates/components/common/criteria.html

1. fixed nested criteria create issue 
2. updates related to matching task rule based on nested criteria groups

matching task rule based on nested criteria

---

src/microbatching/utils/microbatch_rule.py
src/microbatching/views/microbatch_rule.py
src/resource_assigner/utils.py
src/resource_assigner/views/match_rule_task.py

Refactored AssignmentRule and MicrobatchRule matching processes to reduce runtime with big data sets.

enhancement: Optimize match rule process

---

src/job_manager/views/task.py
src/templates/components/common/table.html
src/templates/job_manager/task/child_task.html

fix: dropdown toggle for child task added

---

src/common/utils/views.py
src/common/views/table_view.py

Bug Fix:
Fixed bug for icontains lookup for field like join or forignkey relations in Matching rule criteria

fix: bug fix for icontains lookup 
